---
# ============================================================================
# CloudStack Nested Virtualization - Inventory
# ============================================================================
# This file defines the hosts and their structure.
# For configuration variables, edit: inventory/group_vars/all.yml
# ============================================================================

all:
  children:
    # Physical KVM host (your Ubuntu machine)
    kvm_host:
      hosts:
        localhost:
          ansible_connection: local
          ansible_become_method: sudo
          ansible_become_exe: /usr/bin/sudo.ws
          ansible_become_flags: '-H -S'
          ansible_python_interpreter: /usr/bin/python3

    # Nested VMs for CloudStack infrastructure
    cloudstack_infra:
      children:
        cloudstack_mgmt:
          hosts:
            cs-mgmt:
              ansible_host: 192.168.100.10
              vm_ram: 4096
              vm_vcpus: 2
              vm_disk_size: 50
              
        nfs_storage:
          hosts:
            cs-nfs:
              ansible_host: 192.168.100.11
              vm_ram: 2048
              vm_vcpus: 1
              vm_disk_size: 100
              
        kvm_compute:
          hosts:
            cs-kvm01:
              ansible_host: 192.168.100.20
              vm_ram: 6144
              vm_vcpus: 4
              vm_disk_size: 50
            cs-kvm02:
              ansible_host: 192.168.100.21
              vm_ram: 6144
              vm_vcpus: 4
              vm_disk_size: 50
